spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-icy-fog-avn5tdht-pooler.c-11.us-east-1.aws.neon.tech:5432/neondb?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_AtBXLyv2w1Gz}
spring.datasource.driver-class-name=org.postgresql.Driver